### ISSUE TITLE
How to send PUT request to templated url with Infolink http handler?

### ISSUE THREAD

**Issue by mahmoud-syr** [simplify9/InfolinkAdapters#11]
I need to send a `PUT` request to update a `Pickup` entity through Infolink to an API endpoint. 
Does InfoLink support that use-case? That also goes for `POST` , `PUT` ,  and `DELETE` requests.
For example, I have a pickup entity with code for example `XA123124144` and tenant with code `XYZ` and I need to send a put request to an end-point like `https://something.com/api/pickups/XYZ/XA123124144`. How can I do that through `Infolink`?

**Comment by samerzughul** [comment]
We are working on an update on the HTTP handler to accept a templated URL as a startup value.
I will update you as soon as possible.

**Comment by samerzughul** [comment]
@mahmoud-syr please review our latest commit that supports templating the URL as discussed
